context:
  name: easyscience
  version: "2.4.0"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/easyscience-${{ version }}.tar.gz
  sha256: d1f6df79e922629cb50dfa88ba6817c4183f12cf0d3c0ce16f8ff0d8386467f5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - setuptools-git-versioning
    - pip
  run:
    - python >=${{ python_min }},<3.14
    - asteval
    - lmfit
    - bumps
    - dfo-ls
    - uncertainties
    - numpy
    - scipp
    - pooch
    - matplotlib-base

tests:
  - script: python -c "import easyscience"
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/easyscience/corelib
  summary: Generic logic for easyScience libraries
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MridulS
