context:
  name: easyscience
  version: "2.2.0"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/easyscience-${{ version }}.tar.gz
  sha256: 524253740b907f3cc06d1258abc6797c94349c3bb2f955ec7135122709835738

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling <=1.21.0
    - setuptools-git-versioning
    - pip
  run:
    - python >=${{ python_min }},<3.14
    - asteval
    - bumps
    - dfo-ls
    - lmfit
    - numpy
    - uncertainties
    - scipp

tests:
  - script: python -c "import easyscience"
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/easyscience/corelib
  summary: Generic logic for easyScience libraries
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MridulS
