context:
  name: easyscience
  version: "2.5.1"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/easyscience-${{ version }}.tar.gz
  sha256: 86b92dd24b7703bf563775290cd1803a8b8134ba3b70dc6502719a376cb7303f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - setuptools-git-versioning
    - pip
  run:
    - python >=${{ python_min }}
    - asteval
    - lmfit
    - bumps
    - dfo-ls
    - numpy
    - scipp

tests:
  - script: python -c "import easyscience"
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/easyscience/corelib
  summary: Generic logic for easyScience libraries
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MridulS
